name: Go
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18

      - name: Run Unit Tests
        run: go test -v ./...
